name: images
on:
  push:
    branches: ['**']
permissions:
  contents: read
  packages: write
jobs:
  devcontainer:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v7
      - uses: TheCBaH/devcontainer-action/devcontainer@v1
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
